### ISSUE TITLE
Copying files to clipboard opens Google drive

### ISSUE THREAD

**Issue by crysports** [lfuelling/lrkFM#20] opened 2018-05-19 13:29 UTC
I tried to share some files and clicked on copy to clipboard but instead of copying text to clipboard,the app opens Google drive.

#### How to reproduce
- Long press on a file to select
- Click share and click  copy to clipboard
- The application will take you somewhere else

On Android 7.1.2

**Comment by lfuelling** [comment] 2018-05-19 17:04
That's because you are trying to copy the file. Not it's contents. Since the android clipboard can't handle files, it redirects you to Google Drive. 

I've been planning on an editor feature but I don't know when that's coming.

(related to #19)

**Comment by lfuelling** [comment] 2018-05-19 19:17
Oh okay, I'll look into it!

That's why I wrote "related". :)

**Comment by lfuelling** [comment] 2018-05-19 20:32
Did you use the "share" or the "copy path to clipboard" feature?

**Comment by lfuelling** [comment] 2018-05-21 16:29
Which of those two? 

The "share" feature tries to share the file itself. If this launches Google Drive this is just a fallback from Google because the clipboard can't handle files.

The "copy path to clipboard" feature copies the file's path to clipboard. If this opens Google drive, I'd love to see logs or something like this.

**Comment by lfuelling** [comment] 2018-08-21 21:31
@crysports are you still interested in getting this fixed?

Otherwise I would close this issue.

**Comment by lfuelling** [comment] 2018-09-07 15:51
I am closing this issue as I cannot reproduce it anymore. It is be fixed in 2.0.

**Closed by lfuelling** 2018-09-07 15:51 UTC
Labels: bug
