### ISSUE TITLE
LrkFM 1.6.4: back navigation key press takes the settings activity down its history

### ISSUE THREAD

**Issue by mcyusuf** [lfuelling/lrkFM#13] opened 2018-05-16 17:49 UTC
#### Expected behavior
While using the back navigation, the settings page should return to the main page of the app. And not go back to its previous activities.

#### Actual behavior
Pressing the device back navigation, the settings menu keeps returning to the previously opened pages, and gets to the apps main page after it has returned back to all the previous activity history.

#### How to reproduce
1. Open settings in the side menu
2. Tap on general and edit any preference, then return to the initial settings page.
3. Repeat step 2 for any of general, analytics or ui as many times.
4. Tap the back navigation key, instead of returning to app main page, it would keep returning to all the pages you've opened

* Browser/App version: 1.6.4
* Operating system: android nougat 7.0

**Comment by lfuelling** [comment] 2018-05-16 18:28
I cannot reproduce this behavior with Android P or Nougat. 

On my devices, pressing either the back button in the app or using the back navigation key just goes back to the main menu before returning to the files view, which is expected behavior.

 Can you please post a screen recording of this?

**Comment by mcyusuf** [comment] 2018-05-16 20:29
https://youtu.be/Rxq_-7udx8g
i was trying to say that after the main settings page having those three options (general, analytics and ui), the back key should take one to the files view. but instead it returns to the previous pages i had opened under the settings.

**Comment by lfuelling** [comment] 2018-05-16 21:42
That's what I cannot reproduce with Android > N.

I will download the emulator for N and test it. Do you use a custom rom or have vendor modifications to android?

**Comment by mcyusuf** [comment] 2018-05-17 02:25
Device is Tecno K7. Runs hiOS version.

**Comment by lfuelling** [comment] 2018-05-22 14:54
I just read the comment by this "knowledge" guy on [busy](https://busy.org/@mcyusuf/lrkfm-1-6-4-back-navigation-key-press-takes-the-settings-activity-down-its-history)...

Just to clarify: This **is** actually a bug. This is not expected behavior and only affects some Android versions. 

@mcyusuf please downvote that comment for me as I don't have an account on there 😶

**Comment by lfuelling** [comment] 2018-05-22 15:10
Okay, whatever you think is best :)

**Comment by lfuelling** [comment] 2018-09-07 15:50
I will close this issue as the settings don't consist of multiple screens anymore with the upcoming release.

**Closed by lfuelling** 2018-09-07 15:50 UTC
Labels: bug
